services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: silver-udochki-app
        volumes:
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy

    web:
        image: nginx:alpine
        container_name: silver-udochki-web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: postgres:17
        container_name: silver-udochki-db
        environment:
            POSTGRES_DB: silver-udochki
            POSTGRES_USER: udochki
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U udochki -d silver-udochki" ]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    db-data:
